<?php

namespace Tests\Feature;

use App\Data\Cars;
use App\Models\CarsModel;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CarsModelTest extends TestCase
{
    private CarsModel $cars_model;
    private Cars $cars;

    protected function setUp(): void
    {
        parent::setUp();// TODO: Change the autogenerated stub
        $this->cars_model = $this->app->make(CarsModel::class);
        $this->cars = $this->app->make(Cars::class);
    }

    public function testInsert(): void
    {
     $this->cars->brand = "Mitsubishi";
     $this->cars->type = "Xpander";
     $this->cars->transmisi = "Automatic";
     $this->cars->deskripsi = "qerewreter";
     $this->cars->gambar = "gambar.jpg";

     $insert = $this->cars_model->insert($this->cars);

     self::assertNotNull($insert);
    }

    public function testSelectAll(): void
    {
      $select = $this->cars_model->selectAll();

      self::assertNotNull($select);
    }
}
