<?php

namespace Tests\Feature;

use App\Http\Controllers\UserController;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserControllerTest extends TestCase
{
  protected UserController $user_controller;

  protected function setUp(): void
  {
    parent::setUp(); // TODO: Change the autogenerated stub

    $this->user_controller = $this->app->make(UserController::class);
  }

  public function testTrue(): void
  {
    self::assertTrue(true);
  }

  public function testLoginPage(): void
  {
    $this->get("/login")
      ->assertSeeText("Page | Login");
  }

  public function testPostLoginPage(): void
  {
    $this->post("/login", [
      "username" => "password",
      "password" => "test"
    ])->assertRedirect("/");
  }
}
