<?php

namespace Tests\Feature;

use App\Data\User;
use App\Http\Controllers\UserController;
use App\Service\UserService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserServiceProviderTest extends TestCase
{
    private UserService $user_service;
    private User $user;
    private UserController $user_controller;

    protected function setUp(): void
    {
      parent::setUp(); // TODO: Change the autogenerated stub

      $this->user_service = $this->app->make(UserService::class);
      $this->user = $this->app->make(User::class);
      $this->user_controller = $this->app->make(UserController::class);
    }

    public function testSample(): void
    {
      self::assertTrue(true);
    }
}


