<?php

namespace App\Providers;

use App\Data\Cars;
use App\Http\Controllers\AdminController;
use App\Models\CarsModel;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;

class CarsServiceProvider extends ServiceProvider implements DeferrableProvider
{
  public function provides()
  {
    return [CarsModel::class, AdminController::class]; // TODO: Change the autogenerated stub
  }
  /**
   * Register services.
   *
   * @return void
   */
  public function register()
  {
    $this->app->singleton(CarsModel::class, function ($app) {
      return new CarsModel();
    });

    $this->app->singleton(Cars::class, function ($app) {
      return new Cars();
    });

    $this->app->singleton(AdminController::class, function ($app) {
      return new AdminController($app->make(Cars::class));
    });
  }

  /**
   * Bootstrap services.
   *
   * @return void
   */
  public function boot()
  {
    //
  }
}
